import PatientCard from "../PatientCard";
import SafetyCard from "../SafetyCard";
import ScoreCard from "../ScoreCard";
import SummaryCards from "./SummaryCards";
import PrescriptionViewer from "./PrescriptionViewer";

import { generatePDF } from "../../utils/pdfGenerator";

function Dashboard({ result, preview }) {
  if (!result) return null;

  return (
    <section className="mx-auto mt-16 max-w-7xl space-y-8">

      {/* Header */}
      <div className="rounded-3xl border border-cyan-500/20 bg-white/5 p-8 backdrop-blur-2xl shadow-xl">

        <div className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center">

          <div>
            <h2 className="text-4xl font-bold text-white">
              AI Prescription Analysis
            </h2>

            <p className="mt-3 text-lg text-gray-400">
              Complete analysis generated by{" "}
              <span className="font-semibold text-cyan-400">
                CuraLens AI
              </span>
            </p>
          </div>

          <button
            onClick={() => generatePDF(result)}
            className="rounded-xl bg-gradient-to-r from-green-500 to-emerald-600 px-6 py-3 font-bold text-white transition hover:scale-105"
          >
            Download PDF
          </button>

        </div>

      </div>

      {/* Summary */}
      <SummaryCards result={result} />

      {/* Prescription + Score */}
      <div className="grid gap-8 xl:grid-cols-2">

        <PrescriptionViewer preview={preview} />

        <div className="space-y-8">
          <ScoreCard score={result.score} />
          <SafetyCard safety={result.safety} />
        </div>

      </div>

      {/* Patient + Medicines */}
      <PatientCard data={result} />

    </section>
  );
}

export default Dashboard;