import jsPDF from "jspdf";

export function generatePDF(result) {
  const doc = new jsPDF();

  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.text("CuraLens AI Report", 20, y);

  y += 15;

  // Patient Details
  doc.setFontSize(14);
  doc.text("Patient Information", 20, y);

  y += 10;
  doc.setFontSize(11);

  doc.text(
    `Patient : ${result.patient_name || "Not Detected"}`,
    20,
    y
  );

  y += 8;

  doc.text(
    `Doctor : ${result.doctor_name || "Not Detected"}`,
    20,
    y
  );

  y += 8;

  doc.text(
    `Hospital : ${result.hospital || "Not Detected"}`,
    20,
    y
  );

  y += 15;

  // Medicines
  doc.setFontSize(14);
  doc.text("Medicines", 20, y);

  y += 10;

  doc.setFontSize(11);

  if (result.medicines && result.medicines.length > 0) {

    result.medicines.forEach((medicine, index) => {

      doc.text(
        `${index + 1}. ${medicine.name}`,
        20,
        y
      );

      y += 7;

      doc.text(
        `Dosage : ${medicine.dosage || "-"}`,
        30,
        y
      );

      y += 7;

      doc.text(
        `Frequency : ${medicine.frequency || "-"}`,
        30,
        y
      );

      y += 7;

      doc.text(
        `Duration : ${medicine.duration || "-"}`,
        30,
        y
      );

      y += 10;

      if (y > 270) {
        doc.addPage();
        y = 20;
      }

    });

  }

  // Safety
  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.text("Safety Analysis", 20, y);

  y += 10;

  doc.setFontSize(11);

  doc.text(
    `Overall Risk : ${
      result.safety?.overall_risk || "Unknown"
    }`,
    20,
    y
  );

  y += 8;

  doc.text(
    `AI Score : ${
      result.score?.score || 0
    }%`,
    20,
    y
  );

  y += 15;

  doc.setFontSize(10);

  doc.text(
    "Generated by CuraLens AI",
    20,
    y
  );

  doc.save("CuraLens_Report.pdf");
}